create extension if not exists pgcrypto;

create table public.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  full_name text,
  role text not null default 'client' check (role in ('admin', 'client')),
  created_at timestamptz not null default now()
);

create table public.cameras (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  code text not null,
  name text not null,
  dss_channel_id text not null,
  stream_path text not null,
  location text,
  status text not null default 'offline'
    check (status in ('online', 'offline', 'reconnecting', 'error')),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  unique (code),
  unique (stream_path)
);

create table public.events (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients(id) on delete cascade,
  camera_id uuid not null references public.cameras(id) on delete cascade,
  event_type text not null default 'WATER_LEVEL',
  raw_y double precision not null,
  smoothed_y double precision not null,
  status text not null,
  confidence double precision check (
    confidence is null or (confidence >= 0 and confidence <= 1)
  ),
  message text not null,
  image_path text,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now()
);

create index events_camera_occurred_at_idx
  on public.events (camera_id, occurred_at desc);

create index events_client_occurred_at_idx
  on public.events (client_id, occurred_at desc);

create or replace function public.current_client_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select client_id from public.profiles where id = auth.uid();
$$;

revoke all on function public.current_client_id() from public;
grant execute on function public.current_client_id() to authenticated;

alter table public.clients enable row level security;
alter table public.profiles enable row level security;
alter table public.cameras enable row level security;
alter table public.events enable row level security;

create policy "users can read their client"
  on public.clients for select
  to authenticated
  using (id = public.current_client_id());

create policy "users can read their profile"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

create policy "users can read their cameras"
  on public.cameras for select
  to authenticated
  using (client_id = public.current_client_id());

create policy "users can read their events"
  on public.events for select
  to authenticated
  using (client_id = public.current_client_id());

comment on column public.cameras.dss_channel_id is
  'Stable DSS channel identifier only. Never store a temporary RTSP URL or token.';
